export {default as Kashmir} from './kash';
export {default as Punjab}from './pun';
export {default as Himachal}from './him';
export {default as Delhi}from './del';
export {default as Rajasthan}from './raj';
export {default as Gujrat}from './guj';
export {default as Maharashtra} from './mah';
export {default as Karnataka}from './karna';
export {default as Goa}from './goa';
export {default as Kerala}from './ker';
export {default as TamilNadu}from './tam';
export {default as Andhra}from './andh';
export {default as Telen}from './tel';
export {default as Madhya}from './madh';
export {default as Chattis}from './chattis';
export {default as Orissa}from './ori';
export {default as Jharkhand}from './jh';
export {default as Bihar}from './bi';
export {default as Bengal}from './ben';
export {default as Assam}from './as';
export {default as Uttarakhand}from './uk';
export {default as Up}from './up';
export {default as Sikkim}from './si';
export {default as Meghalaya}from './megh';
export {default as Tripura}from './tri';
export {default as Mizonaga}from './mizo';
export {default as Manipur}from './mani';
export {default as Aru} from './aru';

